version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - u2032
  labels:
  - dependencies
  ignore:
  - dependency-name: org.mockito:mockito-core
    versions:
    - 3.7.7
    - 3.8.0
  - dependency-name: org.asynchttpclient:async-http-client
    versions:
    - 2.12.2
  - dependency-name: org.controlsfx:controlsfx
    versions:
    - 11.0.3
