language: java
notifications:
    slack:
        rooms:
            - tower-app:tJ3Y31nQmpX8UidoGKGDerrc#activity
        on_success: change
        on_failure: always
after_success:
    - mvn clean test jacoco:report coveralls:report
